name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: https://github.com/dx-oss/nix-shell-action@v11
        with:
          script: |
            which node
