oncurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "nixos-gitlab-runner-1"
  url = "https://git.thilo-billerbeck.com"
  token = "gu9-HVLbWCmWBnznS2Y_"
  executor = "docker"
  environment = ["DOCKER_DRIVER=overlay2"]
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.custom]
    run_exec = ""
