name: "Update pinned channels"
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  update-channels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: cachix/install-nix-action@v20
        name: Install Nix
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "GITHUB_TOKEN=${{ secrets.GITHUBTOKEN }} niv update"
        name: Run niv update
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit changes
        with:
          commit_message: updated pinned channels
