name: "Update hosts"
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  update-hosts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: cachix/install-nix-action@v20
        name: Install Nix
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "colmena apply -v"
        if: ${{ github.event_name != 'schedule' }}
        name: Update machines
      - run: nix-shell --run "colmena apply -v --reboot"
        if: ${{ github.event_name == 'schedule' }}
        name: Update machines (with reboot)
